service:
  name: alexa-bitrise-distribute-apk

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  bitriseSkill:
    handler: handler.bitriseSkill
    events:
      - alexaSkill
    
